In [22]:
# mike babb
# created: 2026 08 23
# find five groups of five letters

In [23]:
# standard
import pickle
import os
import sqlite3
from string import ascii_lowercase
from itertools import product, permutations

In [24]:
import pandas as pd
import numpy as np

In [25]:
# define a function to load a pickle
def load_pickle(file_name):
    if os.path.exists(file_name):
        with open(file_name, 'rb') as handle:
            de_pickle = pickle.load(handle)
    else:
        de_pickle = None
        print("file does not exist")
    return de_pickle

In [26]:
char_matrix = load_pickle(file_name = 'char_matrix.pkl')
letter_dict = load_pickle(file_name = 'letter_dict.pkl')
letter_rank_dict = load_pickle(file_name ='letter_rank_dict.pkl')
word_df = load_pickle(file_name = 'word_df.pkl')

C:\Users\babbm\AppData\Local\Temp\ipykernel_47208\773985408.py:5: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  de_pickle = pickle.load(handle)


In [27]:
word_df.head()

,word,lcase,word_id,n_unique_chars,word_score,word_group
0,aalii,aalii,0,3,20449.0,-2134795976539657997
1,Aaron,aaron,1,4,20642.0,5168226787426640364
2,abaca,abaca,2,3,20009.0,7298090979578241273
3,aback,aback,3,4,15456.0,6926502400987240042
4,abaff,abaff,4,3,14038.0,7931255010571806167


In [28]:
word_df.shape

(9972, 6)

In [29]:
# using the word_group, select entries
word_df = word_df.drop_duplicates(subset = ['word_group'])

In [30]:
word_df = word_df.loc[word_df['n_unique_chars'] == 5, :].reset_index(drop = True)

In [31]:
word_df.head()

,word,lcase,word_id,n_unique_chars,word_score,word_group
0,abhor,abhor,22,5,15210.0,-6309929865134252395
1,abide,abide,23,5,16642.0,-3047576767538267104
2,Abies,abies,25,5,17816.0,7894952363982762409
3,abilo,abilo,26,5,16157.0,-4762514508553607400
4,abler,abler,28,5,17943.0,-7669602973530280345


In [32]:
word_df['word_id'] = range(0, word_df.shape[0])

In [39]:
word_df['lcase'].map(lambda x: len(set(x))).describe()

count    4353.0
mean        5.0
std         0.0
min         5.0
25%         5.0
50%         5.0
75%         5.0
max         5.0
Name: lcase, dtype: float64

In [33]:
letter_dict

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}

In [43]:
# build a char_matrix
char_matrix = np.zeros(shape = (word_df.shape[0], 26), dtype = np.int16)
def build_char_matrix(row):
    for l in row['lcase']:
        char_matrix[row['word_id'], letter_dict[l]] += 1

    


In [44]:
outcome = word_df.apply(build_char_matrix, axis = 1)

In [45]:
char_matrix.max()

np.int16(1)

In [46]:
assert word_df.shape[0] == char_matrix.shape[0]

In [47]:
word_df.shape

(4353, 6)

In [49]:
tr1 = char_matrix[0, :]

In [63]:
lm0 = char_matrix.copy()

In [ ]:
grand_output_list = []
for l0 in lm0:
    print(l0)
    temp_output = []
    outcome = (lm0 + l0).max(axis = 1) == 1
    lm1 = lm0[outcome, :]
    for l1 in lm1:
        outcome = (lm1 + l1).max(axis = 1) == 1
        lm2 = lm1[outcome, :]
        for l2 in lm2:
            outcome = (lm2 + l2).max(axis = 1) == 1
            lm3 = lm2[outcome, :]
            for l3 in lm3:
                outcome = (lm3 + l3).max(axis = 1) == 1
                lm4 = lm3[outcome, :]
                if lm4.shape[0] > 0:
                    grand_output_list.append([l0, l1, l2, l3, l4])








[1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0]
[1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[1 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0]
[1 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0]
[1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0]
[1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0]
[1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0]
[1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0]
[1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0]
[1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0]
[1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0]
[1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
[1 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
[1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0]
[1 1 0 0 0 0 0 0 0 0 0 0 0 0

In [ ]:
ncm = char_matrix[outcome, :]
for irow in ncm:
    



(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,)
(26,

In [61]:
testo

array([[0, 0, 2, ..., 0, 0, 0],
       [0, 0, 2, ..., 0, 0, 0],
       [0, 0, 2, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 2, 2],
       [0, 0, 2, ..., 0, 2, 2],
       [0, 0, 0, ..., 0, 2, 2]], shape=(612, 26), dtype=int16)

In [ ]:
# thinking about this wrong... it's a case of letters left....

In [ ]:
word_df.head()

In [ ]:
word_df['lcase_set'] = word_df['lcase'].map(lambda x: set(x))
word_df['lcase_tuple'] = word_df['lcase_set'].map(lambda x: tuple(x))

In [ ]:
# build dictionaries
word_dict = {}
for i_row, my_row in word_df.iterrows():
    word_dict[my_row['lcase']] = my_row['lcase_set']

In [ ]:
import networkx as nx
from itertools import combinations

In [ ]:
myg = nx.Graph()
edge_list = []
for lc0, lc1 in combinations(word_df['lcase'], 2):
    if word_dict[lc0].isdisjoint(word_dict[lc1]):
        #edge_list.append([ms[0], ms[1]])
        myg.add_edge(u_of_edge=lc0, v_of_edge=lc1)


In [ ]:
myg.number_of_edges()

In [ ]:
word_df.head()

In [ ]:
nx.__version__

In [ ]:
#myg_backup = myg.copy()

In [ ]:
# get 100 words
test_list = word_df['lcase'].tolist()[:10]

In [ ]:
test_list

In [ ]:
#myg = myg_backup.copy()
output_list = []
for w0 in word_df['lcase']:    
#for w0 in test_list:
    reject_groupings = set()
    print(w0)
    l0 = [w0, '', '', '', '']
    #output_list.append(l0)        
    # this is immediately adjacent
    w1_set = set(nx.neighbors(G = myg, n = w0))
    fl0 = set(w0)    
    for w1 in w1_set:
        if reject_groupings.isdisjoint(permutations((w0, w1), r = 2)):
            if fl0.isdisjoint(set(w1)):
                fl1 = fl0.copy()
                fl1.update(w1)                 
                l1 = l0[:]
                l1[1] = w1
                #output_list.append(l1)                
                # immediately adjacent candidates        
                w2_set = set(nx.neighbors(G = myg, n = w1))
                w2_set = w2_set.intersection(w1_set)                
                if w2_set:
                    for w2 in w2_set:
                        if reject_groupings.isdisjoint(permutations((w0, w1,w2), r = 2)):
                            if fl1.isdisjoint(set(w2)):
                                fl2 = fl1.copy()
                                fl2.update(w2)
                                l2 = l1[:]
                                l2[2] = w2
                                #output_list.append(l2)                        
                                w3_set = set(nx.neighbors(G = myg, n = w2))                        
                                w3_set = w3_set.intersection(w2_set)                                
                                if w3_set:
                                    for w3 in w3_set:
                                        if reject_groupings.isdisjoint(permutations((w0, w1, w2, w3), r = 2)):                                        
                                            if fl2.isdisjoint(set(w3)):
                                                fl3 = fl2.copy()
                                                fl3.update(w3)
                                                l3 = l2[:]
                                                l3[3] = w3
                                                #output_list.append(l3)    
                                                # print(l3)
                                                w4_set = set(nx.neighbors(G = myg, n = w3))
                                                w4_set = w4_set.intersection(w3_set)
                                                if w4_set:
                                                    for w4 in w4_set:
                                                        if reject_groupings.isdisjoint(permutations((w0, w1, w2, w3, w4), r = 2)):
                                                            if fl3.isdisjoint(set(w4)):
                                                                fl4 = fl3.copy()
                                                                fl4.update(w4)
                                                                l4 = l3[:]
                                                                l4[4] = w4
                                                                output_list.append(l4)    
                                                                print(l4)
                                                else:                                                    
                                                    # compute combos                                                                                                    
                                                    #print(l3)
                                                    #print(w0, w1, w2, w3)
                                                    perms = list(permutations(l3, r = 2))
                                                    #print(perms)
                                                    reject_groupings.update(perms)
                                                    myg.remove_edges_from(perms)


#print('yay')  
#reject_groupings       

In [ ]:
output_list

In [ ]:
len(reject_groupings)

In [ ]:
myg.number_of_edges()

In [ ]:
output_list

In [ ]:
w3_seta

In [ ]:
reject_groupings

In [ ]:
len(testo)

In [ ]:
next_nodes

In [ ]:
myg.nodes(data = 'abhor')

In [ ]:
# this needs to be a recursive function


In [ ]:
test_outcome = np.where(tv1 == 0)[0]

In [ ]:
test_outcome

In [ ]:
outcome = char_matrix - tv1

In [ ]:
outcome

In [ ]:
outcome1 = outcome

In [ ]:
for wid in word_df['word_id'].tolist():
    cw = char_matrix[wid, :]
    
    # t/f list
    outcome = np.abs(char_matrix - cw).sum(1) == 10
    # next word id list
    wil2 = wil1[outcome]
    if wil2.shape[0] > 
    # next char matrix
    cm2 = cm1[outcome, :]
    
    
    # I'll need five different stages of the word_id_list 

    # 


    
    

In [ ]:
)

In [ ]:
tv1 = char_matrix[0, :]

In [ ]:
tv2 = char_matrix[-1, :]

In [ ]:
tv3 = tv2 - tv1

In [ ]:
testo = char_matrix - tv1

In [ ]:
testo

In [ ]:
testo2 = testo[np.abs(testo).sum(1) == 10, :]

In [ ]:
testo2

In [ ]:
# step 2
testo = testo[testo.sum(0)  ]

In [ ]:
# for each row in the char_matrix:
# substract from the chart_matrix:

In [ ]:
np.abs(tv3).sum()

In [ ]:
word_df.iloc[0]

In [ ]:
word_df.iloc[-1]